name: CI pipeline

on: [push, pull_request]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUKE_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: CI/CD build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/CreativeCodersTeam/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Prepare environment
        run: |
          dotnet tool install --global GitVersion.Tool

      - name: Run './build.cmd Restore'
        run: ./build.cmd Restore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
